; [env:advance-hmi]
; platform = https://github.com/Jason2866/platform-espressif32.git
; board = ESP32-S3-WROOM-1-N16R8
; framework = arduino
; monitor_speed = 115200
; board_build.arduino.partitions = partitions.csv
; board_upload.partitions = partitions.csv

; ; Crucial physical hardware settings for the Advance v1.4 Panel
; ;board_build.arduino.memory_type = opi_opi       ; Configures the high-speed Octal flash and PSRAM pathways
; ;board_build.psram_type = opi                     ; Explicitly enables OPI hardware modes

; build_flags = 
;     -DCONFIG_SPIRAM_SPEED_120M=1
;     -D BOARD_HAS_PSRAM                           ; Informs the compiler structures that PSRAM is physically present
;     -D CONFIG_SPIRAM_MODE_OCT=1                 ; Hardens the system configuration to map all 8 pins for OPI bandwidth
;     -mfix-esp32-psram-cache-issue                ; Prevents cache access race conditions during fast DMA transfers

;     ; --- MANDATORY LOVYANGFX RGB HARDWARE PIPELINE DRIVER CONFIGS ---
;     -D LGFX_USE_V1                              ; Forces LovyanGFX modern driver compilation engine
;     -D CONFIG_INITIAL_MAIN_MEM_SIZE=2097152    ; Ensures large internal heaps remain unfragmented

;      -D LV_CONF_INCLUDE_SIMPLE                    ; Informs LVGL to use plain #include "lv_conf.h"
;      -Iinclude                                    ; Forces the compiler to search your local /include directory

; lib_deps = 
;     lvgl/lvgl@8.3.11
;     adafruit/Adafruit BusIO@1.17.0
;     adafruit/Adafruit SSD1306@2.5.13
;     tamctec/TAMC_GT911@^1.0.2
;     robtillaart/TCA9554@0.1.1
;     lovyan03/LovyanGFX@1.2.19

[env:advance-hmi]
platform = https://github.com/Jason2866/platform-espressif32.git
board = ESP32-S3-WROOM-1-N16R8
framework = arduino
monitor_speed = 115200
board_build.arduino.partitions = partitions.csv
board_upload.partitions = partitions.csv

build_flags = 
    -D CONFIG_SPIRAM_SPEED_120M=1
    -D LV_CONF_INCLUDE_SIMPLE
    -Iinclude

lib_deps = 
    lvgl/lvgl@8.3.11
    adafruit/Adafruit BusIO@1.17.0
    adafruit/Adafruit SSD1306@2.5.13
    tamctec/TAMC_GT911@^1.0.2
    robtillaart/TCA9554@0.1.1
    lovyan03/LovyanGFX@1.2.19
