// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: MasterHub

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_LabelTemperature;
extern lv_obj_t * ui_LabelHumidity;
extern void ui_event_ButtonBacklight(lv_event_t * e);
extern lv_obj_t * ui_ButtonBacklight;
extern lv_obj_t * ui_LabelBLButtonText;
extern lv_obj_t * ui_LabelTemperature2;
extern lv_obj_t * ui_LabelHumidity2;
extern lv_obj_t * ui_LabelTime;
extern lv_obj_t * ui_LabelDate;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

