// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: MasterHub

#include "ui.h"

lv_obj_t * ui_MainScreen = NULL;
lv_obj_t * ui_LabelTemperature = NULL;
lv_obj_t * ui_LabelHumidity = NULL;
lv_obj_t * ui_ButtonBacklight = NULL;
lv_obj_t * ui_LabelBLButtonText = NULL;
lv_obj_t * ui_LabelTemperature2 = NULL;
lv_obj_t * ui_LabelHumidity2 = NULL;
lv_obj_t * ui_LabelTime = NULL;
lv_obj_t * ui_LabelDate = NULL;
// event funtions
void ui_event_ButtonBacklight( lv_event_t * e )
   {
   lv_event_code_t event_code = lv_event_get_code( e );

   if( event_code == LV_EVENT_RELEASED )
      {
      EventBLButtonClicked( e );
      }
   }

// build funtions

void ui_MainScreen_screen_init( void )
   {
   ui_MainScreen = lv_obj_create( NULL );
   lv_obj_clear_flag( ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
   lv_obj_set_style_bg_img_src( ui_MainScreen, &ui_img_background_png, LV_PART_MAIN | LV_STATE_DEFAULT );

   ui_LabelTemperature = lv_label_create( ui_MainScreen );
   lv_obj_set_width( ui_LabelTemperature, LV_SIZE_CONTENT ); /// 1
   lv_obj_set_height( ui_LabelTemperature, LV_SIZE_CONTENT );  /// 1
   lv_obj_set_x( ui_LabelTemperature, -170 );
   lv_obj_set_y( ui_LabelTemperature, -184 );
   lv_obj_set_align( ui_LabelTemperature, LV_ALIGN_CENTER );
   lv_label_set_text( ui_LabelTemperature, "86.4 F" );
   lv_obj_clear_flag( ui_LabelTemperature,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
   lv_obj_set_style_text_color( ui_LabelTemperature, lv_color_hex( 0xFFFFFF ), LV_PART_MAIN | LV_STATE_DEFAULT );
   lv_obj_set_style_text_opa( ui_LabelTemperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT );
   lv_obj_set_style_text_font( ui_LabelTemperature, &ui_font_SensorDisplay, LV_PART_MAIN | LV_STATE_DEFAULT );
   lv_obj_set_style_opa( ui_LabelTemperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT );

   ui_LabelHumidity = lv_label_create( ui_MainScreen );
   lv_obj_set_width( ui_LabelHumidity, LV_SIZE_CONTENT ); /// 1
   lv_obj_set_height( ui_LabelHumidity, LV_SIZE_CONTENT );  /// 1
   lv_obj_set_x( ui_LabelHumidity, 214 );
   lv_obj_set_y( ui_LabelHumidity, -184 );
   lv_obj_set_align( ui_LabelHumidity, LV_ALIGN_CENTER );
   lv_label_set_text( ui_LabelHumidity, "56%" );
   lv_obj_clear_flag( ui_LabelHumidity, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
   lv_obj_set_style_text_color( ui_LabelHumidity, lv_color_hex( 0xFFFFFF ), LV_PART_MAIN | LV_STATE_DEFAULT );
   lv_obj_set_style_text_opa( ui_LabelHumidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT );
   lv_obj_set_style_text_font( ui_LabelHumidity, &ui_font_SensorDisplay, LV_PART_MAIN | LV_STATE_DEFAULT );
   lv_obj_set_style_opa( ui_LabelHumidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT );

   ui_ButtonBacklight = lv_btn_create( ui_MainScreen );
   lv_obj_set_width( ui_ButtonBacklight, 150 );
   lv_obj_set_height( ui_ButtonBacklight, 50 );
   lv_obj_set_x( ui_ButtonBacklight, -298 );
   lv_obj_set_y( ui_ButtonBacklight, 183 );
   lv_obj_set_align( ui_ButtonBacklight, LV_ALIGN_CENTER );
   lv_obj_add_flag( ui_ButtonBacklight, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
   lv_obj_clear_flag( ui_ButtonBacklight, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
   lv_obj_set_style_radius( ui_ButtonBacklight, 1, LV_PART_MAIN | LV_STATE_DEFAULT );
   lv_obj_set_style_bg_color( ui_ButtonBacklight, lv_color_hex( 0x404050 ), LV_PART_MAIN | LV_STATE_DEFAULT );
   lv_obj_set_style_bg_opa( ui_ButtonBacklight, 180, LV_PART_MAIN | LV_STATE_DEFAULT );
   lv_obj_set_style_shadow_color( ui_ButtonBacklight, lv_color_hex( 0x000000 ), LV_PART_MAIN | LV_STATE_DEFAULT );
   lv_obj_set_style_shadow_opa( ui_ButtonBacklight, 50, LV_PART_MAIN | LV_STATE_DEFAULT );
   lv_obj_set_style_shadow_width( ui_ButtonBacklight, 2, LV_PART_MAIN | LV_STATE_DEFAULT );
   lv_obj_set_style_shadow_spread( ui_ButtonBacklight, 2, LV_PART_MAIN | LV_STATE_DEFAULT );
   lv_obj_set_style_shadow_ofs_x( ui_ButtonBacklight, 5, LV_PART_MAIN | LV_STATE_DEFAULT );
   lv_obj_set_style_shadow_ofs_y( ui_ButtonBacklight, 5, LV_PART_MAIN | LV_STATE_DEFAULT );

   ui_LabelBLButtonText = lv_label_create( ui_ButtonBacklight );
   lv_obj_set_width( ui_LabelBLButtonText, LV_SIZE_CONTENT ); /// 1
   lv_obj_set_height( ui_LabelBLButtonText, LV_SIZE_CONTENT );  /// 1
   lv_obj_set_x( ui_LabelBLButtonText, -1 );
   lv_obj_set_y( ui_LabelBLButtonText, 1 );
   lv_obj_set_align( ui_LabelBLButtonText, LV_ALIGN_CENTER );
   lv_label_set_text( ui_LabelBLButtonText, "Bright" );
   lv_obj_set_style_text_color( ui_LabelBLButtonText, lv_color_hex( 0xE0E0E0 ), LV_PART_MAIN | LV_STATE_DEFAULT );
   lv_obj_set_style_text_opa( ui_LabelBLButtonText, 255, LV_PART_MAIN | LV_STATE_DEFAULT );
   lv_obj_set_style_text_font( ui_LabelBLButtonText, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT );

   ui_LabelTemperature2 = lv_label_create( ui_MainScreen );
   lv_obj_set_width( ui_LabelTemperature2, LV_SIZE_CONTENT ); /// 1
   lv_obj_set_height( ui_LabelTemperature2, LV_SIZE_CONTENT );  /// 1
   lv_obj_set_x( ui_LabelTemperature2, -169 );
   lv_obj_set_y( ui_LabelTemperature2, -67 );
   lv_obj_set_align( ui_LabelTemperature2, LV_ALIGN_CENTER );
   lv_label_set_text( ui_LabelTemperature2, "---F" );
   lv_obj_clear_flag( ui_LabelTemperature2,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
   lv_obj_set_style_text_color( ui_LabelTemperature2, lv_color_hex( 0xFFFFFF ), LV_PART_MAIN | LV_STATE_DEFAULT );
   lv_obj_set_style_text_opa( ui_LabelTemperature2, 255, LV_PART_MAIN | LV_STATE_DEFAULT );
   lv_obj_set_style_text_font( ui_LabelTemperature2, &ui_font_SensorDisplay, LV_PART_MAIN | LV_STATE_DEFAULT );
   lv_obj_set_style_opa( ui_LabelTemperature2, 255, LV_PART_MAIN | LV_STATE_DEFAULT );

   ui_LabelHumidity2 = lv_label_create( ui_MainScreen );
   lv_obj_set_width( ui_LabelHumidity2, LV_SIZE_CONTENT ); /// 1
   lv_obj_set_height( ui_LabelHumidity2, LV_SIZE_CONTENT );  /// 1
   lv_obj_set_x( ui_LabelHumidity2, 214 );
   lv_obj_set_y( ui_LabelHumidity2, -66 );
   lv_obj_set_align( ui_LabelHumidity2, LV_ALIGN_CENTER );
   lv_label_set_text( ui_LabelHumidity2, "---%" );
   lv_obj_clear_flag( ui_LabelHumidity2,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
   lv_obj_set_style_text_color( ui_LabelHumidity2, lv_color_hex( 0xFFFFFF ), LV_PART_MAIN | LV_STATE_DEFAULT );
   lv_obj_set_style_text_opa( ui_LabelHumidity2, 255, LV_PART_MAIN | LV_STATE_DEFAULT );
   lv_obj_set_style_text_font( ui_LabelHumidity2, &ui_font_SensorDisplay, LV_PART_MAIN | LV_STATE_DEFAULT );
   lv_obj_set_style_opa( ui_LabelHumidity2, 255, LV_PART_MAIN | LV_STATE_DEFAULT );

   ui_LabelTime = lv_label_create( ui_MainScreen );
   lv_obj_set_width( ui_LabelTime, LV_SIZE_CONTENT ); /// 1
   lv_obj_set_height( ui_LabelTime, LV_SIZE_CONTENT );  /// 1
   lv_obj_set_x( ui_LabelTime, 168 );
   lv_obj_set_y( ui_LabelTime, 125 );
   lv_obj_set_align( ui_LabelTime, LV_ALIGN_CENTER );
   lv_label_set_text( ui_LabelTime, "10:16 PM" );
   lv_obj_set_style_text_color( ui_LabelTime, lv_color_hex( 0xFFFFFF ), LV_PART_MAIN | LV_STATE_DEFAULT );
   lv_obj_set_style_text_opa( ui_LabelTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT );
   lv_obj_set_style_text_font( ui_LabelTime, &ui_font_SensorDisplay, LV_PART_MAIN | LV_STATE_DEFAULT );

   ui_LabelDate = lv_label_create( ui_MainScreen );
   lv_obj_set_width( ui_LabelDate, LV_SIZE_CONTENT ); /// 1
   lv_obj_set_height( ui_LabelDate, LV_SIZE_CONTENT );  /// 1
   lv_obj_set_x( ui_LabelDate, 243 );
   lv_obj_set_y( ui_LabelDate, 198 );
   lv_obj_set_align( ui_LabelDate, LV_ALIGN_CENTER );
   lv_label_set_text( ui_LabelDate, "Monday Aug 14, 2026" );
   lv_obj_set_style_text_color( ui_LabelDate, lv_color_hex( 0xFFFFFF ), LV_PART_MAIN | LV_STATE_DEFAULT );
   lv_obj_set_style_text_opa( ui_LabelDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT );
   lv_obj_set_style_text_font( ui_LabelDate, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT );

   lv_obj_add_event_cb( ui_ButtonBacklight, ui_event_ButtonBacklight, LV_EVENT_ALL, NULL );

   }

void ui_MainScreen_screen_destroy( void )
   {
   if( ui_MainScreen )
      {
      lv_obj_del( ui_MainScreen );
      }

   // NULL screen variables
   ui_MainScreen = NULL;
   ui_LabelTemperature = NULL;
   ui_LabelHumidity = NULL;
   ui_ButtonBacklight = NULL;
   ui_LabelBLButtonText = NULL;
   ui_LabelTemperature2 = NULL;
   ui_LabelHumidity2 = NULL;
   ui_LabelTime = NULL;
   ui_LabelDate = NULL;

   }
